// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package a2aexp

import (
	"github.com/stainless-sdks/a2a-exp-go/internal/apierror"
	"github.com/stainless-sdks/a2a-exp-go/packages/param"
	"github.com/stainless-sdks/a2a-exp-go/shared"
)

// aliased to make [param.APIUnion] private when embedding
type paramUnion = param.APIUnion

// aliased to make [param.APIObject] private when embedding
type paramObj = param.APIObject

type Error = apierror.Error

// Represents a file, data structure, or other resource generated by an agent
// during a task.
//
// This is an alias to an internal type.
type Artifact = shared.Artifact

// Represents a single message in the conversation between a user and an agent.
//
// This is an alias to an internal type.
type Message = shared.Message

// Identifies the sender of the message. `user` for the client, `agent` for the
// service.
//
// This is an alias to an internal type.
type MessageRole = shared.MessageRole

// Equals "agent"
const MessageRoleAgent = shared.MessageRoleAgent

// Equals "user"
const MessageRoleUser = shared.MessageRoleUser

// Represents a single message in the conversation between a user and an agent.
//
// This is an alias to an internal type.
type MessageParam = shared.MessageParam

// Defines the parameters for a request to send a message to an agent. This can be
// used to create a new task, continue an existing one, or restart a task.
//
// This is an alias to an internal type.
type MessageSendParams = shared.MessageSendParams

// Optional configuration for the send request.
//
// This is an alias to an internal type.
type MessageSendParamsConfiguration = shared.MessageSendParamsConfiguration

// A discriminated union representing a part of a message or artifact, which can be
// text, a file, or structured data.
//
// This is an alias to an internal type.
type PartUnion = shared.PartUnion

// Represents a text segment within a message or artifact.
//
// This is an alias to an internal type.
type PartTextPart = shared.PartTextPart

// Represents a file segment within a message or artifact. The file content can be
// provided either directly as bytes or as a URI.
//
// This is an alias to an internal type.
type PartFilePart = shared.PartFilePart

// The file content, represented as either a URI or as base64-encoded bytes.
//
// This is an alias to an internal type.
type PartFilePartFileUnion = shared.PartFilePartFileUnion

// Represents a file with its content provided directly as a base64-encoded string.
//
// This is an alias to an internal type.
type PartFilePartFileFileWithBytes = shared.PartFilePartFileFileWithBytes

// Represents a file with its content located at a specific URI.
//
// This is an alias to an internal type.
type PartFilePartFileFileWithUri = shared.PartFilePartFileFileWithUri

// Represents a structured data segment (e.g., JSON) within a message or artifact.
//
// This is an alias to an internal type.
type PartDataPart = shared.PartDataPart

// A discriminated union representing a part of a message or artifact, which can be
// text, a file, or structured data.
//
// This is an alias to an internal type.
type PartUnionParam = shared.PartUnionParam

// Represents a text segment within a message or artifact.
//
// This is an alias to an internal type.
type PartTextPartParam = shared.PartTextPartParam

// Represents a file segment within a message or artifact. The file content can be
// provided either directly as bytes or as a URI.
//
// This is an alias to an internal type.
type PartFilePartParam = shared.PartFilePartParam

// The file content, represented as either a URI or as base64-encoded bytes.
//
// This is an alias to an internal type.
type PartFilePartFileUnionParam = shared.PartFilePartFileUnionParam

// Represents a file with its content provided directly as a base64-encoded string.
//
// This is an alias to an internal type.
type PartFilePartFileFileWithBytesParam = shared.PartFilePartFileFileWithBytesParam

// Represents a file with its content located at a specific URI.
//
// This is an alias to an internal type.
type PartFilePartFileFileWithUriParam = shared.PartFilePartFileFileWithUriParam

// Represents a structured data segment (e.g., JSON) within a message or artifact.
//
// This is an alias to an internal type.
type PartDataPartParam = shared.PartDataPartParam

// Defines the configuration for setting up push notifications for task updates.
//
// This is an alias to an internal type.
type PushNotificationConfig = shared.PushNotificationConfig

// Optional authentication details for the agent to use when calling the
// notification URL.
//
// This is an alias to an internal type.
type PushNotificationConfigAuthentication = shared.PushNotificationConfigAuthentication

// Defines the configuration for setting up push notifications for task updates.
//
// This is an alias to an internal type.
type PushNotificationConfigParam = shared.PushNotificationConfigParam

// Optional authentication details for the agent to use when calling the
// notification URL.
//
// This is an alias to an internal type.
type PushNotificationConfigAuthenticationParam = shared.PushNotificationConfigAuthenticationParam

// Represents a single, stateful operation or conversation between a client and an
// agent.
//
// This is an alias to an internal type.
type Task = shared.Task

// Defines parameters containing a task ID, used for simple task operations.
//
// This is an alias to an internal type.
type TaskIDParams = shared.TaskIDParams

// A container associating a push notification configuration with a specific task.
//
// This is an alias to an internal type.
type TaskPushNotificationConfig = shared.TaskPushNotificationConfig

// A container associating a push notification configuration with a specific task.
//
// This is an alias to an internal type.
type TaskPushNotificationConfigParam = shared.TaskPushNotificationConfigParam

// Represents the status of a task at a specific point in time.
//
// This is an alias to an internal type.
type TaskStatus = shared.TaskStatus

// The current state of the task's lifecycle.
//
// This is an alias to an internal type.
type TaskStatusState = shared.TaskStatusState

// Equals "submitted"
const TaskStatusStateSubmitted = shared.TaskStatusStateSubmitted

// Equals "working"
const TaskStatusStateWorking = shared.TaskStatusStateWorking

// Equals "input-required"
const TaskStatusStateInputRequired = shared.TaskStatusStateInputRequired

// Equals "completed"
const TaskStatusStateCompleted = shared.TaskStatusStateCompleted

// Equals "canceled"
const TaskStatusStateCanceled = shared.TaskStatusStateCanceled

// Equals "failed"
const TaskStatusStateFailed = shared.TaskStatusStateFailed

// Equals "rejected"
const TaskStatusStateRejected = shared.TaskStatusStateRejected

// Equals "auth-required"
const TaskStatusStateAuthRequired = shared.TaskStatusStateAuthRequired

// Equals "unknown"
const TaskStatusStateUnknown = shared.TaskStatusStateUnknown
